import 'bootstrap/dist/css/bootstrap.css';
import '@/styles/globals.scss';
import '@/styles/index.scss';
import type {AppProps} from 'next/app';
import Head from 'next/head';
import {useEffect} from 'react';

if (process.env.NODE_ENV !== 'development') {
   console.log = () => {};
}

export default function App({Component, pageProps}: AppProps) {
   useEffect(() => {
      require('bootstrap/dist/js/bootstrap.js');
      // eslint-disable-next-line react-hooks/exhaustive-deps
   }, []);

   return (
      <>
         <Head>
            <title>Create Next App</title>
            <meta name="description" content="Generated by create next app" />
            <meta name="viewport" content="width=device-width, initial-scale=1" />
            <link rel="icon" href="/favicon.ico" />
         </Head>
         <Component {...pageProps} />
      </>
   );
}

function getInitialProps() {
   return {};
}

App.getInitialProps = getInitialProps;
